---
# Libreria Numpy
- Creación de arreglos numpy
- Funciones preconstruidas de creación de arreglos
- Métodos útiles de arreglos
- Indexación y selección
- Referencia y copia de un arreglo
- Operaciones entre arreglos
- Aplicando funciones a un arreglo

In [1]:
import numpy as np

### Creación de arreglos numpy

In [3]:
mi_lista = [1, 2, 3]
mi_lista

[1, 2, 3]

In [6]:
mi_np_array = np.array(mi_lista)
mi_np_array

array([1, 2, 3])

In [11]:
print(type(mi_np_array))
print(mi_np_array.dtype)

<class 'numpy.ndarray'>
int32


In [12]:
# creacion de una matriz
mi_matriz = [[1,2,3], [4,5,6], [7,8,9]]
mi_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
mi_matriz_np = np.array(mi_matriz)
mi_matriz_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Funciones preconstruidas para creación

In [16]:
# rango de valores de 0 a 10
arr1 = np.arange(10)
print(arr1)

# rango de valores entre 10 y 20
arr1 = np.arange(10,20)
print(arr1)

# rango de valores entre 10 y 20 con incremento 2
arr1 = np.arange(10,20,2)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [18]:
# arreglo de ceros
arr = np.zeros(3)
print(arr)

# matriz de ceros
arr = np.zeros((3,4))
print(arr)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# arreglo de unos
arr = np.ones(3)
print(arr)

arr = np.ones((3,4))
print(arr)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
# vector con distribución de puntos
arr = np.linspace(0,1,5)
print(arr)

arr = np.linspace(0,10,20)
print(arr)

[0.   0.25 0.5  0.75 1.  ]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [24]:
# matriz identidad
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
# arreglos con valores aleatoreos
arr = np.random.rand(4)
print(arr)

arr = np.random.rand(3,3)
print(arr)

[0.1858732  0.74181863 0.2716007  0.83155987]
[[0.71544582 0.75768507 0.86869258]
 [0.2304983  0.73961053 0.03656283]
 [0.89987351 0.0763334  0.4591293 ]]


In [29]:
# entero aleatoreo entre 1 y 100
arr = np.random.randint(1,100)
print(arr)

# arreglo de enteros aleatoreos entre 1 y 100
arr = np.random.randint(1, 100, 10)
print(arr)

85
[82 72 45 35 69 44 35 42 41 78]


In [31]:
# valores aleatoreos distribuidos normalmente
arr = np.random.randn(5)
print(arr)

[-0.18100626 -1.0573989  -0.20052464 -1.72537727 -0.57814916]


### Métodos útiles de arreglos

In [35]:
# redimensionamiento de un arreglo
arr = np.arange(25)
print(arr)

m = arr.reshape(5,5)
print(m)

# dimensionalidad del arreglo
print(m.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [36]:
# redimensionamiento fallido
m = arr.reshape(4,3)

ValueError: cannot reshape array of size 25 into shape (4,3)

In [43]:
arr = np.array([1,3,5,4,2,0])
print(arr)

# máximo valor de un arreglo
print(arr.max())

# mínimo valor de un arreglo
print(arr.min())

# indice del valor maximo
print(arr.argmax())

# indice del valor minimo
print(arr.argmin())

[1 3 5 4 2 0]
5
0
2
5


### Indexación y selección

In [59]:
arr = np.arange(10)

# selección por indice
print(arr[0])

0


In [60]:
# seleccion de rango
print(arr[3:5])

print(arr[3:])
print(arr[:5])

[3 4]
[3 4 5 6 7 8 9]
[0 1 2 3 4]


In [62]:
# asignar un valor
arr[0] = 100

print(arr)

# asignar un rango de valores
arr[:5] = 100
print(arr)

[100 100 100   3   4   5   6   7   8   9]
[100 100 100 100 100   5   6   7   8   9]


In [63]:
# seleccion en una matriz
m = np.arange(9).reshape(3,3)
print(m)

# seleccionar un elemento
print(m[1][0])
print(m[1,0])

# seleccionar un rango de elementos
print(m[1:3,1:3])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
3
3
[[4 5]
 [7 8]]


In [66]:
# seleccion condicional
arr = np.arange(0,11)
print(arr)

print(arr > 5)

print(arr[arr > 5])

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


### Referencia y copia

In [70]:
# el problema de la referencia
arr = np.arange(11)
print(arr)

subset = arr[:5]
print(subset)

subset[:] = 100
print(subset)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [71]:
# copia de un arreglo
arr = np.arange(11)
print(arr)

# copiamos el objeto
subset = arr[:5].copy()
print(subset)

subset[:] = 100
print(subset)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[100 100 100 100 100]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Operaciones entre arreglos

In [87]:
arr = np.arange(10)
print(arr)

# suma de arreglos
print(arr + arr)

# resta
print(arr - arr)

# mult
print(arr*arr)



[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [88]:
# operaciones con escalares
print(arr + 100)
print(arr - 5)
print(arr * 2)
print(arr / 5)
print(arr**3)

[100 101 102 103 104 105 106 107 108 109]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[  0   1   8  27  64 125 216 343 512 729]


In [91]:
# divisiones por cero
print(arr/arr)

# infinito
print(1/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\jsepulveda\Anaconda3\envs\dataanalysis\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\jsepulveda\Anaconda3\envs\dataanalysis\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


### Aplicando funciones a un arreglo

In [85]:
arr = np.arange(10)
print(arr)

# maximo
print(np.max(arr))

# minimo
print(np.min(arr))

# sin
print(np.sin(arr))

# cos
print(np.cos(arr))

[0 1 2 3 4 5 6 7 8 9]
9
0
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]


In [93]:
# sqrt
print(np.sqrt(arr))

# exp
print(np.exp(arr))

# log
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\jsepulveda\Anaconda3\envs\dataanalysis\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
