---
# Guia ejercicios Numpy - Solución



#### Importar la librería con su alias

In [2]:
import numpy as np

#### 1. Cree un arreglo de diez elementos con valor 1

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 2. Cree un arreglo de diez elementos con valor 100

In [8]:
np.ones(10) * 100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

#### 3. Cree un arreglo entre 30 y 90 con múltiplos de 3

In [10]:
np.arange(30,93,3)

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78,
       81, 84, 87, 90])

#### 4. Cree una matriz de 5x5 con valores consecutivos que partan en 1

In [4]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 5. Cree una matriz identidad de dimensiones 5x5

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 6. Cree una matriz como la siguiente utilizando multiplicación de arreglos

In [6]:
np.arange(1,26).reshape(5,5) * np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  7.,  0.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.],
       [ 0.,  0.,  0., 19.,  0.],
       [ 0.,  0.,  0.,  0., 25.]])

#### 7. Genere un arreglo de 10 números aleatorios entre 1 millón y 90 millones

In [17]:
np.random.randint(1e6, 9e7, 10)

array([21415623, 18186362, 63365849, 18053285,  9726676, 12824676,
       12837608, 18979595, 49445327, 50283326])

#### 8. Genere una matriz de 5x4 con números distribuidos de forma normal

In [23]:
np.random.randn(5,4)

array([[ 0.78539222,  0.07396051,  1.39921569, -1.08085886],
       [-0.044366  ,  1.28389966,  1.68199233, -0.4534034 ],
       [-1.27018571,  0.07075397, -0.50034694,  0.32015866],
       [-0.15501072,  0.04617529, -0.73283463,  0.54221407],
       [ 0.40287836,  0.04775223, -0.15975731, -0.66970302]])

#### 9. Genere una matriz tridimensional de 2x3x4 con números aleatorios enteros entre 1 y 9

In [31]:
np.random.randint(1,10,(2,3,4))

array([[[3, 1, 2, 7],
        [7, 3, 1, 4],
        [4, 6, 2, 9]],

       [[9, 6, 8, 2],
        [7, 2, 4, 1],
        [6, 1, 5, 1]]])

#### 10. Genere la siguiente matriz

In [35]:
np.arange(1,51).reshape(5,10) / 10

array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ],
       [3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ],
       [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ]])

#### 11. Cree un arreglo de 50 puntos linealmente espaciados entre -1 y 1

In [36]:
np.linspace(-1,1,50)

array([-1.        , -0.95918367, -0.91836735, -0.87755102, -0.83673469,
       -0.79591837, -0.75510204, -0.71428571, -0.67346939, -0.63265306,
       -0.59183673, -0.55102041, -0.51020408, -0.46938776, -0.42857143,
       -0.3877551 , -0.34693878, -0.30612245, -0.26530612, -0.2244898 ,
       -0.18367347, -0.14285714, -0.10204082, -0.06122449, -0.02040816,
        0.02040816,  0.06122449,  0.10204082,  0.14285714,  0.18367347,
        0.2244898 ,  0.26530612,  0.30612245,  0.34693878,  0.3877551 ,
        0.42857143,  0.46938776,  0.51020408,  0.55102041,  0.59183673,
        0.63265306,  0.67346939,  0.71428571,  0.75510204,  0.79591837,
        0.83673469,  0.87755102,  0.91836735,  0.95918367,  1.        ])

#### 12. Cree un arreglo con al menos 50 puntos lineamente espaciados entre -1 y 1 que contenga el valor cero

In [38]:
np.linspace(-1,1,51)

array([-1.  , -0.96, -0.92, -0.88, -0.84, -0.8 , -0.76, -0.72, -0.68,
       -0.64, -0.6 , -0.56, -0.52, -0.48, -0.44, -0.4 , -0.36, -0.32,
       -0.28, -0.24, -0.2 , -0.16, -0.12, -0.08, -0.04,  0.  ,  0.04,
        0.08,  0.12,  0.16,  0.2 ,  0.24,  0.28,  0.32,  0.36,  0.4 ,
        0.44,  0.48,  0.52,  0.56,  0.6 ,  0.64,  0.68,  0.72,  0.76,
        0.8 ,  0.84,  0.88,  0.92,  0.96,  1.  ])

#### Para los siguientes ejercios considere la siguiente matriz mat de 5x10

In [59]:
mat = np.arange(1,51).reshape(5,10)
mat

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

#### 13. A partir de la matriz mat, cree dos matrices de 5x5, la primera de ellas con las primeras 5 columnas, y la segunda matriz con las columnas restantes

In [60]:
mat1 = mat[:,:5].copy()
mat2 = mat[:,5:].copy()
print('mat1=')
print(mat1, '\n')
print('mat2=')
print(mat2)

mat1=
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]] 

mat2=
[[ 6  7  8  9 10]
 [16 17 18 19 20]
 [26 27 28 29 30]
 [36 37 38 39 40]
 [46 47 48 49 50]]


#### 14. Entregue un arreglo con las sumas de las columnas de mat1

In [61]:
mat1.sum(axis=0)

array([105, 110, 115, 120, 125])

#### 15. Haga una multiplicación elemento a elemento entre mat1 y mat2

In [62]:
mat1*mat2

array([[   6,   14,   24,   36,   50],
       [ 176,  204,  234,  266,  300],
       [ 546,  594,  644,  696,  750],
       [1116, 1184, 1254, 1326, 1400],
       [1886, 1974, 2064, 2156, 2250]])

#### 16. Entregue una matriz con la diagonal de la matriz obtenida en el punto anterior

In [63]:
mat1*mat2*np.eye(5)

array([[   6.,    0.,    0.,    0.,    0.],
       [   0.,  204.,    0.,    0.,    0.],
       [   0.,    0.,  644.,    0.,    0.],
       [   0.,    0.,    0., 1326.,    0.],
       [   0.,    0.,    0.,    0., 2250.]])

#### 17. Realice una multiplicación matricial entre m1 y m2 (utilice el método dot)

In [64]:
mat1.dot(mat2)

array([[ 490,  505,  520,  535,  550],
       [1790, 1855, 1920, 1985, 2050],
       [3090, 3205, 3320, 3435, 3550],
       [4390, 4555, 4720, 4885, 5050],
       [5690, 5905, 6120, 6335, 6550]])

#### 18. Haga una multiplicación matricial entre m1 y la matriz identidad

In [66]:
mat1.dot(np.eye(5))

array([[ 1.,  2.,  3.,  4.,  5.],
       [11., 12., 13., 14., 15.],
       [21., 22., 23., 24., 25.],
       [31., 32., 33., 34., 35.],
       [41., 42., 43., 44., 45.]])

---