In [1]:
#arreglos numericos#
arrNum=[4,5,6,7]
print(arrNum)

[4, 5, 6, 7]


In [2]:
for a in arrNum:
    print(a)

4
5
6
7


In [17]:
#numpy: libreria de python para almacenar datos en vectores y matrices#
import numpy as np
np.array([[1,2,3],[4,5,6],[7,8,9]])

class Persona:
    def __init__(self,rut,nombre,apellido):
        self.rut=rut
        self.nombre=nombre
        self.apellido=apellido
p1=Persona(17456234,"Maria","Gutierrez")
p2=Persona(12398123,"Marcos","Luna")
p3=Persona(13120380,"Luis","Nuñez")

arrPersona=np.array([[p1],[p2],[p3]])
arrPersona


array([[<__main__.Persona object at 0x000002CC7238B460>],
       [<__main__.Persona object at 0x000002CC723A03A0>]], dtype=object)

In [27]:
a=np.arange(6,77,12)
print(a)

[ 6 18 30 42 54 66]


In [26]:
a.reshape(3,2)

array([[ 6, 18],
       [30, 42],
       [54, 66]])

In [28]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [32]:
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [34]:
np.random.randint(0,100,size=100)

array([28, 15, 58, 89, 14, 62, 59, 49, 13, 61,  8, 75, 22, 59, 48, 73, 86,
       76,  5, 54, 93, 36, 61, 53, 90, 79, 11,  1, 26, 65, 51,  1, 46, 87,
       35, 18, 93, 91, 89, 30, 38, 54, 79, 62, 86, 78, 88, 88, 47, 89, 99,
       22,  1,  6, 38, 57, 67, 78, 97, 74, 23, 45, 98, 51, 16, 83,  0,  0,
       14, 52, 95, 71, 11, 53, 54, 11, 12, 62, 32, 80, 24, 30, 18, 53,  7,
        2, 26, 12, 89, 96, 85, 40, 62, 39, 83, 72, 35, 72, 99, 64])

In [1]:
#actividad de compra de entradas#
#programa Nico#
class Cliente:
    arrNombres=[]
    arrApellidos=[]
    arrRun=[]
    def __init__(self,nombre,apellido,run):
        self.nombre=nombre
        self.apellido=apellido
        self.run=run
    inicio=0
    final=0
    print("Programa de compra de entradas para chayanne")
    print("Si desea comprar presione 1 si no presione 0")
    if inicio!=0:
        nombre=input("favor ingrese su nombre")
        apellido=input("favor ingrese su apellido")
        run=input("favor ingrese su run")
        
        

Programa de compra de entradas para chayanne
Si desea comprar presione 1 si no presione 0


In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,6])

f = np.array([a,b])

f.sum(axis=0)
f.sum(axis=1)

array([15, 16])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 6]])